services:
    ioc.extra.jinja2.loader:
        class:  jinja2.ChoiceLoader
        arguments:
            - ['@ioc.extra.jinja2.module_loader']

    ioc.extra.jinja2.module_loader:
        class:  jinja2.PrefixLoader
        arguments:
            - '%ioc.extra.jinja2.loader_mapping%'
        kwargs:
            delimiter: ':'

    ioc.extra.jinja2:
        class: jinja2.Environment
        kwargs: # custom value
            autoescape: true 
            cache_size: 200  
            loader: '@ioc.extra.jinja2.loader'
